### ISSUE TITLE
v0.1.2 Blank Screen

### ISSUE THREAD

**Issue by hwong103** [vignaesh01/sfdx-command-builder#2]
Haven't come across this before. Been a regular user of this extension for a while now and suddenly I'm now finding that the extension doesn't load. Not sure the best way to explain it without taking a screencap

https://is.gd/9BYUzW

Any ideas?

Version: 1.46.1 (system setup)
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by vignaesh01** [comment]
Hi @hwong103 
Please try the below steps

Reauthenticate your org with your sfdx project

If still the issue persists, please send me the extension logs & developer tools log.

Steps for Extension logs:
Help -> Toggle Developer Tools
View -> Command Palette -> Developer : Open Logs Folder

Steps for Developer tools log:
View -> Command Palette -> Developer : Open Webview Developer Tools

**Comment by hwong103** [comment]
Hey @vignaesh01 

Thanks so much for looking into this. In terms of reauthenticating I created a new scratch org yesterday so that should be enough right?

Please find the logs attached

[console-1592990838701.log](https://github.com/vignaesh01/sfdx-command-builder/files/4824408/console-1592990838701.log)

[output_logging_20200624T192211.zip](https://github.com/vignaesh01/sfdx-command-builder/files/4824394/output_logging_20200624T192211.zip)

**Comment by vignaesh01** [comment]
Hi @hwong103 ,
 The issue has been fixed now. Please install the latest version of the extension and check it out.

Thanks
